# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: set PKG_CONFIG_PATH environment variable
      run: |
        echo "PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Download, build, and install SDL2 packages
      run: |
        wget https://www.libsdl.org/release/SDL2-$SDL_VERSION.tar.gz
        tar xf SDL2-$SDL_VERSION.tar.gz
        cd SDL2-$SDL_VERSION
        ./configure --prefix=$HOME/.local
        make install
        cd ..
        wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-$IMG_VERSION.tar.gz
        tar xf SDL2_image-$IMG_VERSION.tar.gz
        cd SDL2_image-$IMG_VERSION
        ./configure --prefix=$HOME/.local
        make install
        cd ..
        wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-$MIX_VERSION.tar.gz
        tar xf SDL2_mixer-$MIX_VERSION.tar.gz
        cd SDL2_mixer-$MIX_VERSION
        ./configure --prefix=$HOME/.local
        make install
        cd ..
        wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-$TTF_VERSION.tar.gz
        tar xf SDL2_ttf-$TTF_VERSION.tar.gz
        cd SDL2_ttf-$TTF_VERSION
        ./configure --prefix=$HOME/.local
        make install
        cd ..

    - name: Test if Go-SDL2 works with the SDL2 packages
      run: |
        go build ./{sdl,img,mix,ttf}
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Format
      run: go fmt -v ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4.0.0
      
            
